language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
script: xvfb-run bundle exec rspec spec
before_script:
  - psql -c 'create database review_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
    email:
        - rdunlop@thoughtworks.com
